### PR TITLE
Add environment variables.

### PR DESCRIPTION
**Pull request by nrwiersma**
Hi,

Started playing with your library. It is really cool. Wanted to add logging and environment variables.

### CODE REVIEW

**Comment by jasonmoo** [comment]
Hi.  Thanks for the feedback.  I think you may be wanting `STDERR` for your logging.  `log.Println("find me in the logs")` for example.  

The `process.env` addition looks nice.  Can you rework the pr to only include that?

**Comment by nrwiersma** [comment]
Hi. 

You are right, `STDERR` make far more sense.
Will work on the pull request now.

**Comment by jasonmoo** [comment]
Hi.  So I remembered that the child process inherits the environment from the nodejs process by default.  So I think we should be ok without this too.  Are you not able to access lambda environment variables from go?

https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

**Comment by nrwiersma** [comment]
Huh. Will have to look into this. Thanks.

**Pull request closed without merging**
