### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by davyzhang**
There's a chance for json parse wrong with special characters like '\u001b',  try to wrap it  a little bit and log properly for inspections later.

### CODE REVIEW

**Comment by jasonmoo** [comment]
Great catch.

Perhaps something like this would be even more helpful?:

``` javascript
} catch(err) {
    done({
        "error": err.toString('UTF-8'),
        "payload": data.toString('UTF-8')
    });
}

// Outputs:
// {"error":"SyntaxError: Unexpected token \u001b","payload":"{\"a\":\"\u001bb\"}"}
```

**Comment by davyzhang** [comment]
nice change, it would be more readabel

**Comment by jasonmoo** [comment]
Hey do you mind explaining how you're causing this exception?  In my local tests I haven't been able to cause a `JSON.parse` exception.

**Comment by davyzhang** [comment]
Hi,

The last time I met exceptions was because some control characters
like "\u001B"
were mixed in the string.

**Comment by jasonmoo** [comment]
Ok I'm not able to reproduce the bug you're reporting but will add the exception handling.

**Comment by jasonmoo** [comment]
Added in 49abf10

**Pull request closed without merging**
